level_1 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX      E   XXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX T      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X T E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXETX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX                     X",
            "XX          EXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XXT          XXXX       X",
            "XXXE                   TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_2 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XTP               E T  XX",
            "XX   X  XX X  XXXXXXX   X",
            "XX   X  XX   XXX  X X   X",
            "X   XXXXX    XX  XX X   X",
            "XX      XXXX    XXX X  XX",
            "XXXXXX  XXXX   XX   X   X",
            "X      XXXXXXX   XXXXX  X",
            "X  X   XXXXXXXXX   E    X",
            "X XXX  XXXXXXXX    XXXXXX",
            "X XXXX  XX       XXXXXXXX",
            "X XXXXX     X      XXXXXX",
            "X XXXXX  XXXX    XXX   X",
            "X X     XXXXXXXX  XX XXXX",
            "X  TX      XXX     X XXXX",
            "X  XXX  X         XX XXXX",
            "X  XXX  XX  XXXX XXX XXXX",
            "X  XXX  XX  XXXX  XX XXXX",
            "X  XXX  XX  X          TX",
            "XE XXX  XX XX  XXXXX XXX",
            "XXXXXX  XX     XXXXXX XXX",
            "XXTE    XX  XXX  E     XX",
            "XX X  XXX   XX  XXXXXX  X",
            "X E         XX   XXXXX TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

blank_maze = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]