level_1 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX      E   XXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX T      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X T E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXETX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX                     X",
            "XX          EXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XXT          XXXX       X",
            "XXXE                   TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_2 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XT                E T  XX",
            "XX      XXXXXXXXXXXXX   X",
            "XXX  X  X    XXX  X X   X",
            "X   XXXXX    XX  XX X   X",
            "X       XXXX    XXX X  XX",
            "XXXXXX  XXXX    X   X   X",
            "X      XXXXXXX   XXXXX  X",
            "X  X   XXXXXXXXX   E    X",
            "X XXX  XXXXXXXX    XXXX X",
            "X XXXX  XX       XXX    X",
            "X XXXXX     X     XX  XXX",
            "X XXXXX  XXXX      X   TX",
            "X X     XXXXXXXX   X XX X",
            "X  TX      XXX     X XX X",
            "X  XXX  X     P   XX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  X     E    TX",
            "XE XXX  XX XX  XXXXX  XXX",
            "XXXXXX  XX     XXXXX  XXX",
            "XXTE    XX  XXX  E     XX",
            "XX XXXXXX   XX  XXXX X  X",
            "X E         XX   XXX X TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

blank_maze = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]